containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
      - "ALL"
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1001
