global:
  storageClass: 'local-path'
  postgresql:
    auth:
      postgresPassword: 'postgres'
      username: 'admin'
      password: 'password'
      database: 'database'
    service:
      ports:
        postgresql: ''
primary:
  persistence:
    mountPath: '/bitnami/postgresql'
    size: '3Gi'
