#cloud-config
ssh_pwauth: true
groups:
  - stream
users:
  - name: user
    # gecos: "Coop R. Kneads"
    # primary_group: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: 
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBrOblt31lj96vEylh7OduuoDkn4WAaO6xQ8YRA2vZBY brk@fed
hostname: "${hostname}.${domain}"
packages:
  - python3-pip
write_files:
  - path: /tmp/bootstrap.sh
    content: |
      #!/bin/bash
      set -eux
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.28.9+k3s1 INSTALL_K3S_EXEC="--disable traefik" sh -s -
      install -o stream -g stream -m 0644 /etc/rancher/k3s/k3s.yaml /home/stream/kubeconfig
runcmd:
  - bash /tmp/bootstrap.sh
