#cloud-config
ssh_pwauth: true
groups:
  - captain
users:
  - name: captain
    # gecos: "Coop R. Kneads"
    primary_group: captain
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: 
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBrOblt31lj96vEylh7OduuoDkn4WAaO6xQ8YRA2vZBY brk@fed
hostname: "${hostname}"
fqdn: ${hostname}.${domain}"
packages:
  - python3-pip
write_files:
  - path: /tmp/init-upgrade.sh
    content: |
      dnf update -y
      systemctl reboot
runcmd:
  - bash /tmp/init-upgrade.sh
