#cloud-config
ssh_pwauth: true
groups:
  - user
users:
  - name: user
    # gecos: "Coop R. Kneads"
    primary_group: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: 
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBrOblt31lj96vEylh7OduuoDkn4WAaO6xQ8YRA2vZBY brk@fed
hostname: "${hostname}.${domain}"
packages:
  - python3-pip
write_files:
  - path: /tmp/bootstrap.sh
    content: |
      #!/bin/bash
      set -eux
      curl -sfL https://get.rke2.io | sh -
      systemctl enable --now rke2-server.service
      install -o user -g user -m 0644 /etc/rancher/rke2/rke2.yaml /home/user/kubeconfig
      echo 'PATH=$PATH:/var/lib/rancher/rke2/bin/' > /etc/profile.d/path-rke2.sh
runcmd:
  - bash /tmp/bootstrap.sh
