apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cn-postgres
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: 'cloudnative-pg'
    targetRevision: '0.20.2'
    helm:
      releaseName: 'cnpg'
      # valueFiles:
      #   - $repo/argocd/values/cn-postgres.yaml
  # - repoURL: 'https://github.com/kirici/homelab.git'
  #   targetRevision: 'master'
  #   ref: 'repo'
  - repoURL: 'https://github.com/kirici/homelab.git'
    path: 'argocd/resources/cn-postgres'
    targetRevision: 'master'
    directory:
      recurse: true
  destination:
    namespace: cn-postgres
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
