apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: 'postgresql'
    targetRevision: '15.2.5'
    helm:
      releaseName: 'postgresql'
      valueFiles:
      - $repo/argocd/values/postgresql.yaml
  - repoURL: 'https://github.com/kirici/homelab.git'
    targetRevision: 'master'
    ref: 'repo'
  destination:
    namespace: postgresql
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
