apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-aio
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.rook.io/release'
    chart: 'rook-ceph-cluster'
    targetRevision: 'v1.17.4'
  - repoURL: 'https://github.com/kirici/homelab.git'
    targetRevision: 'master'
    path: 'argocd/resources/rook-ceph-aio'
    directory:
      recurse: true
  destination:
    namespace: rook-ceph
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
