apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: v0.27.0
    chart: vault
    helm:
      values: |
        global:
          tlsDisable: true
        ui:
          enabled: true
  destination:
    namespace: vault
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
