nameOverride: "promstack"
crds:
  enabled: true
defaultRules:
  create: true
  rules:
    alertmanager: false
    windows: false
prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: false
alertmanager:
  enabled: false
grafana:
  enabled: true
  adminPassword: 'admin'
  persistence:
    enabled: true
    type: 'pvc'
    storageClassName: 'local-path'
    accessModes:
      - ReadWriteOnce
    size: '2Gi'
    finalizers:
      - kubernetes.io/pvc-protection
  service:
    portName: http-web
