apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsig-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsig-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: selfsig-ca
  secretName: ca-root
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsig-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-root
